name: openhotel
services:
    web:
        restart: unless-stopped
        container_name: openhotel
        ports:
            - '9980:9980'
            - '2002:2002'
        volumes:
            - 'openhotel-data:/app'
        image: 'openhotel/openhotel:latest'
volumes:
    openhotel-data: null
