name: openhotel
services:
    web:
        restart: unless-stopped
        container_name: openhotel
        ports:
            - '1994:1994'
            - '2002:2002'
            - '2005:2005'
        volumes:
            - 'openhotel-data:/app'
        image: 'openhotel/openhotel:latest'
volumes:
    openhotel-data: null
